spring:
  application:
    name: task-service

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      initialization-fail-timeout: -1
      maximumPoolSize: 20
      minimumIdle: 5
      idleTimeout: 30000
      maxLifetime: 600000

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: ${SPRING_RABBITMQ_PORT}
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}

    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 5s
          max-attempts: 10
          multiplier: 2

  jpa:
    hibernate:
      ddl-auto: validate

services:
  authentication:
    url: http://authentication-service:8080/
  profile:
    url: http://profile-service:8081/

server:
  port: 8082