spring:
  application:
    name: authentication-service

  datasource:
    url: ${SPRING_DATASOURCE_URL_AUTH}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: ${SPRING_RABBITMQ_PORT}
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}

  init:
    admin-email: ${ADMIN_EMAIL}
    admin-password: ${ADMIN_PASSWORD}

jwt:
  signerKey: ${JWT_SIGNER_KEY}
  valid-duration: ${JWT_VALID_DURATION}
  refreshable-duration: ${JWT_REFRESHABLE_DURATION}

server:
  port: 8080