services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/migrations/01_init_authentication_service.sql:/docker-entrypoint-initdb.d/01_init_authentication_service.sql
      - ./database/migrations/02_init_task_service.sql:/docker-entrypoint-initdb.d/02_init_task_service.sql
    networks:
      - db-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
    profiles: [ "auth", "task", "full" ]

  auth-service:
    build: ./backend/authentication-service
    container_name: auth-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}?currentSchema=auth_schema
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      JWT_SIGNER_KEY: ${JWT_SIGNER_KEY}
      JWT_VALID_DURATION: ${JWT_VALID_DURATION}
      JWT_REFRESHABLE_DURATION: ${JWT_REFRESHABLE_DURATION}
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network
      - db-network
    profiles: [ "auth", "full" ]

  neo4j:
    image: neo4j:2026.01.4-community-ubi10
    container_name: neo4j_db
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: ${NEO4J_AUTH}
    volumes:
      - neo4j_data:/data
    networks:
      - db-network
    healthcheck:
      test: [ "CMD", "neo4j", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    profiles: [ "profile", "full" ]

  profile-service:
    build: ./backend/profile-service
    container_name: profile-service
    environment:
      SPRING_NEO4J_URI: bolt://neo4j:7687
      SPRING_NEO4J_AUTHENTICATION_USERNAME: neo4j
      SPRING_NEO4J_AUTHENTICATION_PASSWORD: ${NEO4J_PASSWORD}
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
    depends_on:
      neo4j:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network
      - db-network
    profiles: [ "profile", "full" ]

  task-service:
    build: ./backend/task-service
    container_name: task-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}?currentSchema=task_schema
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network
      - db-network
    profiles: [ "task", "full" ]

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/
      - rabbitmq-log:/var/log/rabbitmq/
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    profiles: [ "auth", "profile", "task", "full" ]

  api-gateway:
    build: ./backend/api-gateway
    container_name: api-gateway
    ports:
      - "8888:8888"
    networks:
      - app-network
    profiles: [ "frontend", "auth", "profile", "task", "full" ]

  frontend:
    build: ./frontend
    container_name: task_frontend
    ports:
      - "3000:80"
    depends_on:
      - api-gateway
    networks:
      - app-network
    profiles: [ "frontend", "full" ]

volumes:
  postgres_data:
  neo4j_data:
  rabbitmq-data:
  rabbitmq-log:

networks:
  app-network:
  db-network: