services:
  postgres:
    image: postgres:16
    container_name: postgres
    shm_size: '256mb'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/migrations/01_init_authentication_service.sql:/docker-entrypoint-initdb.d/01_init_authentication_service.sql
      - ./database/migrations/02_init_task_service.sql:/docker-entrypoint-initdb.d/02_init_task_service.sql
    networks:
      - db-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 300s
    labels:
      - "autoheal=true"

  neo4j:
    image: neo4j:2026.01.4-community-ubi10
    container_name: neo4j
    environment:
      NEO4J_AUTH: ${NEO4J_AUTH}
    volumes:
      - neo4j_data:/data
    networks:
      - db-network
    healthcheck:
      test: [ "CMD", "neo4j", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 420s
    labels:
      - "autoheal=true"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/
      - rabbitmq-log:/var/log/rabbitmq/
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 240s
    labels:
      - "autoheal=true"

  mongodb:
    image: mongo:7.0
    container_name: mongodb 
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DB}
    volumes:
      - mongodb_data:/data/db
      - ./database/migrations/01_init_mongodb.js:/docker-entrypoint-initdb.d/01_init_mongodb.js
    networks:
      - db-network
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --eval 'db.runCommand(\"ping\").ok' localhost:27017/admin -u ${MONGODB_USERNAME} -p ${MONGODB_PASSWORD} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 300s
    labels:
      - "autoheal=true"

  authentication-service:
    restart: unless-stopped
    image: ghcr.io/nguyentin05/task-management/authentication-service:latest
    container_name: authentication-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}?currentSchema=${AUTHENTICATION_SCHEMA}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      JWT_SIGNER_KEY: ${JWT_SIGNER_KEY}
      JWT_VALID_DURATION: ${JWT_VALID_DURATION}
      JWT_REFRESHABLE_DURATION: ${JWT_REFRESHABLE_DURATION}
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network
      - db-network
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O /dev/null http://localhost:8080/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 120s
    labels:
      - "autoheal=true"

  profile-service:
    restart: unless-stopped
    image: ghcr.io/nguyentin05/task-management/profile-service:latest
    container_name: profile-service
    environment:
      SPRING_NEO4J_URI: bolt://neo4j:7687
      SPRING_NEO4J_AUTHENTICATION_USERNAME: ${NEO4J_USERNAME}
      SPRING_NEO4J_AUTHENTICATION_PASSWORD: ${NEO4J_PASSWORD}
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
    depends_on:
      neo4j:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network
      - db-network
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O /dev/null http://localhost:8081/actuator/health || exit 1"]
      interval: 10s     
      timeout: 5s
      retries: 3
      start_period: 120s
    labels:
      - "autoheal=true"

  task-service:
    restart: unless-stopped
    image: ghcr.io/nguyentin05/task-management/task-service:latest
    container_name: task-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}?currentSchema=${TASK_SCHEMA}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network
      - db-network
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O /dev/null http://localhost:8082/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 120s
    labels:
      - "autoheal=true"

  comment-service:
    restart: unless-stopped
    image: ghcr.io/nguyentin05/task-management/comment-service:latest
    container_name: comment-service
    environment:
      SPRING_MONGODB_URI: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongodb:27017/${MONGODB_DB}
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network
      - db-network
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O /dev/null http://localhost:8083/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 120s
    labels:
      - "autoheal=true"

  notification-service:
    restart: unless-stopped
    image: ghcr.io/nguyentin05/task-management/notification-service:latest
    container_name: notification-service
    environment:
      NOTIFICATION_EMAIL_BREVO_APIKEY: ${NOTIFICATION_EMAIL_BREVO_APIKEY}
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O /dev/null http://localhost:8084/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 120s
    labels:
      - "autoheal=true"

  api-gateway:
    image: ghcr.io/nguyentin05/task-management/api-gateway:latest
    restart: unless-stopped
    container_name: api-gateway
    ports:
      - "8888:8888"
    depends_on:
      authentication-service:
        condition: service_healthy
      profile-service:
        condition: service_healthy
      task-service:
        condition: service_healthy
      comment-service:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O /dev/null http://localhost:8888/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 120s
    labels:
      - "autoheal=true"

  frontend:
    image: ghcr.io/nguyentin05/task-management/frontend:latest
    restart: unless-stopped
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - api-gateway
    networks:
      - app-network
    labels:
      - "autoheal=true"

  autoheal:
    image: willfarrell/autoheal
    restart: always
    container_name: autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=autoheal
      - AUTOHEAL_START_PERIOD=300
      - AUTOHEAL_INTERVAL=10
      - AUTOHEAL_DEFAULT_STOP_TIMEOUT=10
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network

volumes:
  postgres_data:
  neo4j_data:
  rabbitmq-data:
  rabbitmq-log:
  mongodb_data:

networks:
  app-network:
  db-network:
