spring:
  application:
    name: profile-service

  neo4j:
    uri: ${SPRING_NEO4J_URI}
    authentication:
      username: ${SPRING_NEO4J_AUTHENTICATION_USERNAME}
      password: ${SPRING_NEO4J_AUTHENTICATION_PASSWORD}

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: ${SPRING_RABBITMQ_PORT}
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 5s
          max-attempts: 10
          multiplier: 2

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

server:
  port: 8081