graph TB
  linkStyle default fill:#ffffff

  subgraph diagram ["System Context View: Task Management"]
    style diagram fill:#ffffff,stroke:#ffffff

    1["<div style='font-weight: bold'>User</div><div style='font-size: 70%; margin-top: 0px'>[Person]</div><div style='font-size: 80%; margin-top:10px'>End User</div>"]
    style 1 fill:#ffffff,stroke:#4c8a1e,color:#4c8a1e
    2["<div style='font-weight: bold'>Administrator</div><div style='font-size: 70%; margin-top: 0px'>[Person]</div><div style='font-size: 80%; margin-top:10px'>Administrator</div>"]
    style 2 fill:#ffffff,stroke:#4c8a1e,color:#4c8a1e
    3("<div style='font-weight: bold'>Task Management</div><div style='font-size: 70%; margin-top: 0px'>[Software System]</div><div style='font-size: 80%; margin-top:10px'>Task Management - Trello<br />Clone</div>")
    style 3 fill:#ffffff,stroke:#005696,color:#005696
    93("<div style='font-weight: bold'>Brevo</div><div style='font-size: 70%; margin-top: 0px'>[Software System]</div><div style='font-size: 80%; margin-top:10px'>SMTP</div>")
    style 93 fill:#ffffff,stroke:#bf1e2e,color:#bf1e2e
    94("<div style='font-weight: bold'>Cloudinary</div><div style='font-size: 70%; margin-top: 0px'>[Software System]</div><div style='font-size: 80%; margin-top:10px'>Media Management SaaS</div>")
    style 94 fill:#ffffff,stroke:#f29100,color:#f29100

    3-. "<div>Reads from and writes to</div><div style='font-size: 70%'>[HTTPS/REST]</div>" .->94
    3-. "<div>Reads from and writes to</div><div style='font-size: 70%'>[HTTPS/REST]</div>" .->93
    1-. "<div>Add project, task, comment,<br />...</div><div style='font-size: 70%'></div>" .->3
    2-. "<div>Manage user, workspace,<br />project, task, comment, ...</div><div style='font-size: 70%'></div>" .->3

  end