graph TB
  linkStyle default fill:#ffffff

  subgraph diagram ["Component View: Notification Service"]
    style diagram fill:#ffffff,stroke:#ffffff

    93("<div style='font-weight: bold'>Brevo</div><div style='font-size: 70%; margin-top: 0px'>[Software System]</div><div style='font-size: 80%; margin-top:10px'>SMTP</div>")
    style 93 fill:#ffffff,stroke:#bf1e2e,color:#bf1e2e

    subgraph 3 ["Task Management"]
      style 3 fill:#ffffff,stroke:#005696,color:#005696

      subgraph 52 ["Notification Service"]
        style 52 fill:#ffffff,stroke:#005696,color:#005696

        53("<div style='font-weight: bold'>Consumer</div><div style='font-size: 70%; margin-top: 0px'>[Component: Spring]</div><div style='font-size: 80%; margin-top:10px'>Consumer</div>")
        style 53 fill:#ffffff,stroke:#005696,color:#005696
        54("<div style='font-weight: bold'>Service</div><div style='font-size: 70%; margin-top: 0px'>[Component: Spring]</div><div style='font-size: 80%; margin-top:10px'>Service</div>")
        style 54 fill:#ffffff,stroke:#005696,color:#005696
        55("<div style='font-weight: bold'>Repository Httpclient</div><div style='font-size: 70%; margin-top: 0px'>[Component: Openfeign]</div><div style='font-size: 80%; margin-top:10px'>Repository Httpclient</div>")
        style 55 fill:#ffffff,stroke:#005696,color:#005696
      end

      58["<div style='font-weight: bold'>Message Broker</div><div style='font-size: 70%; margin-top: 0px'>[Container: RabbitMQ]</div><div style='font-size: 80%; margin-top:10px'>Message Broker</div>"]
      style 58 fill:#ffffff,stroke:#005696,color:#005696
    end

    55-. "<div>Reads from and writes to</div><div style='font-size: 70%'>[HTTPS/REST]</div>" .->93
    53-. "<div></div><div style='font-size: 70%'></div>" .->54
    54-. "<div></div><div style='font-size: 70%'></div>" .->55
    53-. "<div>Subscribe event</div><div style='font-size: 70%'></div>" .->58

  end