@startuml
title <size:24>Dynamic View: Task Management</size>\n<size:24>Luồng tìm kiếm User qua OpenFeign</size>

set separator none
left to right direction

<style>
  root {
    BackgroundColor: #ffffff
    FontColor: #444444
  }
</style>

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>

System_Boundary("TaskManagement_boundary", "Task Management", $tags="") {
  Container(TaskManagement.TaskService, "Task Service", $techn="Spring Boot", $descr="Task Service", $tags="", $link="")
  Container(TaskManagement.AuthenticationService, "Authentication Service", $techn="Spring Boot", $descr="Authentication Service", $tags="", $link="")
  Container(TaskManagement.UI, "UI", $techn="React", $descr="Single Page Application", $tags="", $link="")
  Container(TaskManagement.APIGateway, "API Gateway", $techn="Spring Cloud Gateway", $descr="API Gateway", $tags="", $link="")
  Container(TaskManagement.ProfileService, "Profile Service", $techn="Spring Boot", $descr="Profile Service", $tags="", $link="")
}

Person(User, "User", $descr="End User", $tags="", $link="")

Rel(User, TaskManagement.UI, "1: 1. Gõ keyword (email/name)", $techn="", $tags="", $link="")
Rel(TaskManagement.UI, TaskManagement.APIGateway, "2: 2. GET /api/tasks/search-users", $techn="JSON/HTTP", $tags="", $link="")
Rel(TaskManagement.APIGateway, TaskManagement.TaskService, "3: 3. Forward request", $techn="", $tags="", $link="")
Rel(TaskManagement.TaskService, TaskManagement.AuthenticationService, "4: 4. Fetch Auth info (Feign Client)", $techn="OpenFeign/HTTP", $tags="", $link="")
Rel(TaskManagement.TaskService, TaskManagement.ProfileService, "5: 5. Fetch Profile info (Feign Client)", $techn="OpenFeign/HTTP", $tags="", $link="")

SHOW_LEGEND(true)
hide stereotypes
@enduml