graph TB
  linkStyle default fill:#ffffff

  subgraph diagram ["Dynamic View: Task Management"]
    style diagram fill:#ffffff,stroke:#ffffff

    subgraph 3 ["Task Management"]
      style 3 fill:#ffffff,stroke:#005696,color:#005696

      16("<div style='font-weight: bold'>Task Service</div><div style='font-size: 70%; margin-top: 0px'>[Container: Spring Boot]</div><div style='font-size: 80%; margin-top:10px'>Task Service</div>")
      style 16 fill:#ffffff,stroke:#005696,color:#005696
      30("<div style='font-weight: bold'>Authentication Service</div><div style='font-size: 70%; margin-top: 0px'>[Container: Spring Boot]</div><div style='font-size: 80%; margin-top:10px'>Authentication Service</div>")
      style 30 fill:#ffffff,stroke:#005696,color:#005696
      4["<div style='font-weight: bold'>UI</div><div style='font-size: 70%; margin-top: 0px'>[Container: React]</div><div style='font-size: 80%; margin-top:10px'>Single Page Application</div>"]
      style 4 fill:#ffffff,stroke:#005696,color:#005696
      5("<div style='font-weight: bold'>API Gateway</div><div style='font-size: 70%; margin-top: 0px'>[Container: Spring Cloud Gateway]</div><div style='font-size: 80%; margin-top:10px'>API Gateway</div>")
      style 5 fill:#ffffff,stroke:#005696,color:#005696
      58["<div style='font-weight: bold'>Message Broker</div><div style='font-size: 70%; margin-top: 0px'>[Container: RabbitMQ]</div><div style='font-size: 80%; margin-top:10px'>Message Broker</div>"]
      style 58 fill:#ffffff,stroke:#005696,color:#005696
      59[("<div style='font-weight: bold'>Profile DB</div><div style='font-size: 70%; margin-top: 0px'>[Container: Neo4j]</div><div style='font-size: 80%; margin-top:10px'>Graph DBMS</div>")]
      style 59 fill:#ffffff,stroke:#005696,color:#005696
      6("<div style='font-weight: bold'>Profile Service</div><div style='font-size: 70%; margin-top: 0px'>[Container: Spring Boot]</div><div style='font-size: 80%; margin-top:10px'>Profile Service</div>")
      style 6 fill:#ffffff,stroke:#005696,color:#005696
      60[("<div style='font-weight: bold'>Task DB</div><div style='font-size: 70%; margin-top: 0px'>[Container: PostgreSQL]</div><div style='font-size: 80%; margin-top:10px'>RDBMS</div>")]
      style 60 fill:#ffffff,stroke:#005696,color:#005696
      61[("<div style='font-weight: bold'>Authentication DB</div><div style='font-size: 70%; margin-top: 0px'>[Container: PostgreSQL]</div><div style='font-size: 80%; margin-top:10px'>RDBMS</div>")]
      style 61 fill:#ffffff,stroke:#005696,color:#005696
    end

    1["<div style='font-weight: bold'>User</div><div style='font-size: 70%; margin-top: 0px'>[Person]</div><div style='font-size: 80%; margin-top:10px'>End User</div>"]
    style 1 fill:#ffffff,stroke:#4c8a1e,color:#4c8a1e

    1-. "<div>1. 1. Submit form</div><div style='font-size: 70%'></div>" .->4
    4-. "<div>2. 2. POST /api/auth/register</div><div style='font-size: 70%'>[JSON/HTTP]</div>" .->5
    5-. "<div>3. 3. Forward request</div><div style='font-size: 70%'></div>" .->30
    30-. "<div>4. 4. Lưu thông tin User mới</div><div style='font-size: 70%'>[JDBC]</div>" .->61
    30-. "<div>5. 5. Publish 'user.created'<br />event</div><div style='font-size: 70%'></div>" .->58
    6-. "<div>6. 6. Subscribe<br />'user.created' event</div><div style='font-size: 70%'></div>" .->58
    6-. "<div>7. 7. Tạo default Profile</div><div style='font-size: 70%'>[Bolt]</div>" .->59
    16-. "<div>8. 8. Subscribe<br />'user.created' event</div><div style='font-size: 70%'></div>" .->58
    16-. "<div>9. 9. Tạo default Workspace</div><div style='font-size: 70%'>[JDBC]</div>" .->60

  end