graph LR
  linkStyle default fill:#ffffff

  subgraph diagram ["Dynamic View: Task Management - Task Service"]
    style diagram fill:#ffffff,stroke:#ffffff

    subgraph 3 ["Task Management"]
      style 3 fill:#ffffff,stroke:#005696,color:#005696

      subgraph 16 ["Task Service"]
        style 16 fill:#ffffff,stroke:#005696,color:#005696

        17("<div style='font-weight: bold'>Security Filter Chain</div><div style='font-size: 70%; margin-top: 0px'>[Component: Spring Security]</div><div style='font-size: 80%; margin-top:10px'>Security Filter Chain</div>")
        style 17 fill:#ffffff,stroke:#005696,color:#005696
        18("<div style='font-weight: bold'>Controller</div><div style='font-size: 70%; margin-top: 0px'>[Component: Spring]</div><div style='font-size: 80%; margin-top:10px'>Controller</div>")
        style 18 fill:#ffffff,stroke:#005696,color:#005696
        19("<div style='font-weight: bold'>Service</div><div style='font-size: 70%; margin-top: 0px'>[Component: Spring]</div><div style='font-size: 80%; margin-top:10px'>Service</div>")
        style 19 fill:#ffffff,stroke:#005696,color:#005696
        20("<div style='font-weight: bold'>Repository</div><div style='font-size: 70%; margin-top: 0px'>[Component: Spring]</div><div style='font-size: 80%; margin-top:10px'>Repository</div>")
        style 20 fill:#ffffff,stroke:#005696,color:#005696
      end

      5("<div style='font-weight: bold'>API Gateway</div><div style='font-size: 70%; margin-top: 0px'>[Container: Spring Cloud Gateway]</div><div style='font-size: 80%; margin-top:10px'>API Gateway</div>")
      style 5 fill:#ffffff,stroke:#005696,color:#005696
      60[("<div style='font-weight: bold'>Task DB</div><div style='font-size: 70%; margin-top: 0px'>[Container: PostgreSQL]</div><div style='font-size: 80%; margin-top:10px'>RDBMS</div>")]
      style 60 fill:#ffffff,stroke:#005696,color:#005696
    end

    5("<div style='font-weight: bold'>API Gateway</div><div style='font-size: 70%; margin-top: 0px'>[Container: Spring Cloud Gateway]</div><div style='font-size: 80%; margin-top:10px'>API Gateway</div>")
    style 5 fill:#ffffff,stroke:#005696,color:#005696
    60[("<div style='font-weight: bold'>Task DB</div><div style='font-size: 70%; margin-top: 0px'>[Container: PostgreSQL]</div><div style='font-size: 80%; margin-top:10px'>RDBMS</div>")]
    style 60 fill:#ffffff,stroke:#005696,color:#005696

    5-. "<div>1. 1. GET<br />/api/projects/{id}/columns</div><div style='font-size: 70%'></div>" .->17
    17-. "<div>2. 2. Forward request</div><div style='font-size: 70%'></div>" .->18
    18-. "<div>3. 3.<br />getColumnsWithTasks(projectId)</div><div style='font-size: 70%'></div>" .->19
    19-. "<div>4. 4. Query joined data /<br />Aggregation</div><div style='font-size: 70%'></div>" .->20
    20-. "<div>5. 5. SELECT columns,<br />tasks...</div><div style='font-size: 70%'>[JDBC]</div>" .->60

  end