graph LR
  linkStyle default fill:#ffffff

  subgraph diagram ["Dynamic View: Task Management"]
    style diagram fill:#ffffff,stroke:#ffffff

    subgraph 3 ["Task Management"]
      style 3 fill:#ffffff,stroke:#005696,color:#005696

      4["<div style='font-weight: bold'>UI</div><div style='font-size: 70%; margin-top: 0px'>[Container: React]</div><div style='font-size: 80%; margin-top:10px'>Single Page Application</div>"]
      style 4 fill:#ffffff,stroke:#005696,color:#005696
      5("<div style='font-weight: bold'>API Gateway</div><div style='font-size: 70%; margin-top: 0px'>[Container: Spring Cloud Gateway]</div><div style='font-size: 80%; margin-top:10px'>API Gateway</div>")
      style 5 fill:#ffffff,stroke:#005696,color:#005696
      59[("<div style='font-weight: bold'>Profile DB</div><div style='font-size: 70%; margin-top: 0px'>[Container: Neo4j]</div><div style='font-size: 80%; margin-top:10px'>Graph DBMS</div>")]
      style 59 fill:#ffffff,stroke:#005696,color:#005696
      6("<div style='font-weight: bold'>Profile Service</div><div style='font-size: 70%; margin-top: 0px'>[Container: Spring Boot]</div><div style='font-size: 80%; margin-top:10px'>Profile Service</div>")
      style 6 fill:#ffffff,stroke:#005696,color:#005696
    end

    1["<div style='font-weight: bold'>User</div><div style='font-size: 70%; margin-top: 0px'>[Person]</div><div style='font-size: 80%; margin-top:10px'>End User</div>"]
    style 1 fill:#ffffff,stroke:#4c8a1e,color:#4c8a1e
    94("<div style='font-weight: bold'>Cloudinary</div><div style='font-size: 70%; margin-top: 0px'>[Software System]</div><div style='font-size: 80%; margin-top:10px'>Media Management SaaS</div>")
    style 94 fill:#ffffff,stroke:#f29100,color:#f29100

    1-. "<div>1. 1. Chọn ảnh và upload</div><div style='font-size: 70%'></div>" .->4
    4-. "<div>2. 2. POST<br />/api/profiles/avatar</div><div style='font-size: 70%'>[JSON/HTTP]</div>" .->5
    5-. "<div>3. 3. Forward request</div><div style='font-size: 70%'></div>" .->6
    6-. "<div>4. 4. Upload & get secure_url</div><div style='font-size: 70%'>[HTTPS/REST]</div>" .->94
    6-. "<div>5. 5. Cập nhật URL vào Graph<br />Node</div><div style='font-size: 70%'>[Bolt]</div>" .->59

  end