spring:
  application:
    name: comment-service

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: ${SPRING_RABBITMQ_PORT}
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 5s
          max-attempts: 10
          multiplier: 2

  mongodb:
    uri: ${SPRING_MONGODB_URI}

resilience4j:
  circuitbreaker:
    instances:
      authentication-service:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
      profile-service:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
  timelimiter:
    instances:
      authentication-service:
        timeout-duration: 3s
      profile-service:
        timeout-duration: 3s

services:
  authentication:
    url: http://authentication-service:8080/
  profile:
    url: http://profile-service:8081/

server:
  port: 8083