spring:
  application:
    name: comment-service

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: ${SPRING_RABBITMQ_PORT}
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 5s
          max-attempts: 10
          multiplier: 2

  data:
    mongodb:
      host: ${SPRING_MONGODB_HOST}
      port: ${SPRING_MONGODB_PORT}
      database: ${SPRING_MONGODB_DB}
      username: ${SPRING_MONGODB_USERNAME}
      password: ${SPRING_MONGODB_PASSWORD}
      authentication-database: admin

server:
  port: 8083