spring:
  application:
    name: comment-service

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: ${SPRING_RABBITMQ_PORT}
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 5s
          max-attempts: 10
          multiplier: 2

  mongodb:
    uri: ${SPRING_MONGODB_URI}

server:
  port: 8083