title Dynamic View: Task Management\nLuồng xóa Task và trigger xóa Comment qua Event

actor <<Person>>\nUser as User
participant <<Container>>\nUI as UI
participant <<Container>>\nAPI Gateway as API Gateway
participant <<Container>>\nTask Service as Task Service
participant <<Container>>\nTask DB as Task DB
participant <<Container>>\nMessage Broker as Message Broker
participant <<Container>>\nComment Service as Comment Service
participant <<Container>>\nComment DB as Comment DB

User->UI: 1. Bấm xóa Task
UI->API Gateway: 2. DELETE /api/tasks/{id}
API Gateway->Task Service: 3. Xóa Task trong DB
Task Service->Task DB: 4. Xóa  Task
Task Service->Message Broker: 5. Publish 'task.deleted' event
Comment Service->Message Broker: 6. Subscribe event
Comment Service->Comment DB: 7. Xóa toàn bộ Comment của Task
