server:
  port: 8888

app:
  api-prefix: /api/v1

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: authentication_service
              uri: http://authentication-service:8080
              predicates:
                - Path=${app.api-prefix}/auth/**, ${app.api-prefix}/internal/auth/**
              filters:
                - StripPrefix=2
            - id: profile_service
              uri: http://profile-service:8081
              predicates:
                - Path=${app.api-prefix}/profiles/**, ${app.api-prefix}/internal/profiles/**
              filters:
                - StripPrefix=2
            - id: task_service
              uri: http://task-service:8082
              predicates:
                - Path=${app.api-prefix}/tasks/**, ${app.api-prefix}/workspaces/**, ${app.api-prefix}/projects/**, ${app.api-prefix}/columns/**
              filters:
                - StripPrefix=2
            - id: comment_service
              uri: http://comment-service:8083
              predicates:
                - Path=${app.api-prefix}/comments/**
              filters:
                - StripPrefix=2

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    reactor.netty: DEBUG