openapi: 3.1.0
info:
  title: Task Service API
  description: API Docs cho authentication service
  version: "1.0"
servers:
- url: http://localhost
  description: Generated server url
security:
- bearerAuth: []
paths:
  /auth/users/{userId}/roles:
    put:
      tags:
      - user-controller
      operationId: updateRoles
      parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RoleUpdateRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApiResponseUserResponse"
  /auth/users/{userId}/reset-password:
    put:
      tags:
      - user-controller
      operationId: resetPassword
      parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PasswordResetRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApiResponseVoid"
  /auth/users/me/change-password:
    put:
      tags:
      - user-controller
      operationId: changePassword
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PasswordChangeRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApiResponseVoid"
  /internal/auth/introspect:
    post:
      tags:
      - internal-authentication-controller
      operationId: introspect
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TokenIntrospectRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApiResponseIntrospectResponse"
  /auth/users:
    get:
      tags:
      - user-controller
      operationId: getAllUser
      parameters:
      - name: page
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 1
      - name: size
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 20
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApiResponsePageResponseUserResponse"
    post:
      tags:
      - user-controller
      operationId: create
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserCreationRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApiResponseUserResponse"
  /auth/users/register:
    post:
      tags:
      - user-controller
      operationId: register
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserRegisterRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApiResponseUserResponse"
  /auth/token:
    post:
      tags:
      - authentication-controller
      operationId: authenticate
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AuthenticationRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApiResponseAuthenticationResponse"
  /auth/refresh:
    post:
      tags:
      - authentication-controller
      operationId: refresh
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TokenRefreshRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApiResponseAuthenticationResponse"
  /auth/logout:
    post:
      tags:
      - authentication-controller
      operationId: logout
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LogoutRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApiResponseVoid"
  /internal/auth/users/search:
    get:
      tags:
      - internal-authentication-controller
      operationId: search
      parameters:
      - name: email
        in: query
        required: false
        schema:
          type: string
      - name: userIds
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApiResponseListUserSearchResponse"
  /auth/users/{userId}:
    get:
      tags:
      - user-controller
      operationId: getDetail
      parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApiResponseUserResponse"
    delete:
      tags:
      - user-controller
      operationId: delete
      parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApiResponseVoid"
  /auth/users/me:
    get:
      tags:
      - user-controller
      operationId: getMyInfo
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApiResponseUserResponse"
  /auth/roles:
    get:
      tags:
      - role-controller
      operationId: getAllRole
      parameters:
      - name: page
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 1
      - name: size
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 5
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApiResponsePageResponseRoleResponse"
components:
  schemas:
    RoleUpdateRequest:
      type: object
      properties:
        roles:
          type: array
          items:
            type: string
          uniqueItems: true
      required:
      - roles
    ApiResponseUserResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        result:
          $ref: "#/components/schemas/UserResponse"
    RoleResponse:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
    UserResponse:
      type: object
      properties:
        id:
          type: string
        email:
          type: string
        roles:
          type: array
          items:
            $ref: "#/components/schemas/RoleResponse"
          uniqueItems: true
    PasswordResetRequest:
      type: object
      properties:
        newPassword:
          type: string
          maxLength: 255
          minLength: 0
      required:
      - newPassword
    ApiResponseVoid:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        result:
          type: object
    PasswordChangeRequest:
      type: object
      properties:
        oldPassword:
          type: string
        newPassword:
          type: string
          maxLength: 255
          minLength: 0
      required:
      - newPassword
      - oldPassword
    TokenIntrospectRequest:
      type: object
      properties:
        token:
          type: string
      required:
      - token
    ApiResponseIntrospectResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        result:
          $ref: "#/components/schemas/IntrospectResponse"
    IntrospectResponse:
      type: object
      properties:
        valid:
          type: boolean
    UserCreationRequest:
      type: object
      properties:
        email:
          type: string
          maxLength: 255
          minLength: 0
        password:
          type: string
          maxLength: 255
          minLength: 0
        firstName:
          type: string
          maxLength: 255
          minLength: 0
        lastName:
          type: string
          maxLength: 255
          minLength: 0
        roles:
          type: array
          items:
            type: string
          uniqueItems: true
      required:
      - email
      - firstName
      - lastName
      - password
    UserRegisterRequest:
      type: object
      properties:
        email:
          type: string
          maxLength: 255
          minLength: 0
        password:
          type: string
          maxLength: 255
          minLength: 0
        firstName:
          type: string
          maxLength: 255
          minLength: 0
        lastName:
          type: string
          maxLength: 255
          minLength: 0
      required:
      - email
      - firstName
      - lastName
      - password
    AuthenticationRequest:
      type: object
      properties:
        email:
          type: string
          maxLength: 255
          minLength: 0
        password:
          type: string
          maxLength: 255
          minLength: 0
      required:
      - email
      - password
    ApiResponseAuthenticationResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        result:
          $ref: "#/components/schemas/AuthenticationResponse"
    AuthenticationResponse:
      type: object
      properties:
        token:
          type: string
        authenticated:
          type: boolean
    TokenRefreshRequest:
      type: object
      properties:
        token:
          type: string
      required:
      - token
    LogoutRequest:
      type: object
      properties:
        token:
          type: string
      required:
      - token
    ApiResponseListUserSearchResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        result:
          type: array
          items:
            $ref: "#/components/schemas/UserSearchResponse"
    UserSearchResponse:
      type: object
      properties:
        id:
          type: string
        email:
          type: string
    ApiResponsePageResponseUserResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        result:
          $ref: "#/components/schemas/PageResponseUserResponse"
    PageResponseUserResponse:
      type: object
      properties:
        currentPage:
          type: integer
          format: int32
        totalPages:
          type: integer
          format: int32
        pageSize:
          type: integer
          format: int32
        totalElements:
          type: integer
          format: int64
        data:
          type: array
          items:
            $ref: "#/components/schemas/UserResponse"
    ApiResponsePageResponseRoleResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        result:
          $ref: "#/components/schemas/PageResponseRoleResponse"
    PageResponseRoleResponse:
      type: object
      properties:
        currentPage:
          type: integer
          format: int32
        totalPages:
          type: integer
          format: int32
        pageSize:
          type: integer
          format: int32
        totalElements:
          type: integer
          format: int64
        data:
          type: array
          items:
            $ref: "#/components/schemas/RoleResponse"
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
