openapi: 3.1.0
info:
  title: Task Service API
  description: API Docs cho profile service
  version: "1.0"
servers:
- url: http://localhost
  description: Generated server url
security:
- bearerAuth: []
paths:
  /profiles/{profileId}/avatar:
    put:
      tags:
      - profile-controller
      operationId: updateAvatar
      parameters:
      - name: profileId
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/AvatarUpdateRequest"
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApiResponseAvatarResponse"
  /profiles/me/avatar:
    put:
      tags:
      - profile-controller
      operationId: updateMyAvatar
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/AvatarUpdateRequest"
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApiResponseAvatarResponse"
  /profiles/{profileId}:
    get:
      tags:
      - profile-controller
      operationId: getProfile
      parameters:
      - name: profileId
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApiResponseProfileResponse"
    patch:
      tags:
      - profile-controller
      operationId: updateProfile
      parameters:
      - name: profileId
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProfileUpdateRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApiResponseProfileResponse"
  /profiles/me:
    get:
      tags:
      - profile-controller
      operationId: getMyProfile
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApiResponseProfileResponse"
    patch:
      tags:
      - profile-controller
      operationId: updateMyProfile
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProfileUpdateRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApiResponseProfileResponse"
  /profiles:
    get:
      tags:
      - profile-controller
      operationId: getAllProfile
      parameters:
      - name: page
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 1
      - name: size
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 20
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApiResponsePageResponseProfileResponse"
  /internal/profiles/search:
    get:
      tags:
      - internal-profile-controller
      operationId: searchByUserIds
      parameters:
      - name: userIds
        in: query
        required: true
        schema:
          type: array
          items:
            type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApiResponseListProfileSearchResponse"
components:
  schemas:
    AvatarUpdateRequest:
      type: object
      properties:
        avatar:
          type: string
          format: binary
      required:
      - avatar
    ApiResponseAvatarResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        result:
          $ref: "#/components/schemas/AvatarResponse"
    AvatarResponse:
      type: object
      properties:
        avatar:
          type: string
    ProfileUpdateRequest:
      type: object
      properties:
        firstName:
          type: string
          maxLength: 255
          minLength: 0
        lastName:
          type: string
          maxLength: 255
          minLength: 0
        dob:
          type: string
          format: date
        phoneNumber:
          type: string
    ApiResponseProfileResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        result:
          $ref: "#/components/schemas/ProfileResponse"
    ProfileResponse:
      type: object
      properties:
        id:
          type: string
        userId:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        dob:
          type: string
          format: date
        phoneNumber:
          type: string
        avatar:
          type: string
    ApiResponsePageResponseProfileResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        result:
          $ref: "#/components/schemas/PageResponseProfileResponse"
    PageResponseProfileResponse:
      type: object
      properties:
        currentPage:
          type: integer
          format: int32
        totalPages:
          type: integer
          format: int32
        pageSize:
          type: integer
          format: int32
        totalElements:
          type: integer
          format: int64
        data:
          type: array
          items:
            $ref: "#/components/schemas/ProfileResponse"
    ApiResponseListProfileSearchResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        result:
          type: array
          items:
            $ref: "#/components/schemas/ProfileSearchResponse"
    ProfileSearchResponse:
      type: object
      properties:
        userId:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        avatar:
          type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
