@startuml
title <size:24>System Context View: Task Management</size>\n<size:24>The system context diagram for a Task Management System</size>

set separator none
top to bottom direction

<style>
  root {
    BackgroundColor: #ffffff
    FontColor: #444444
  }
</style>

!include <C4/C4>
!include <C4/C4_Context>

Person(User, "User", $descr="End User", $tags="", $link="")
Person(Administrator, "Administrator", $descr="Administrator", $tags="", $link="")
System(TaskManagement, "Task Management", $descr="Task Management - Trello Clone", $tags="", $link="")
System(Brevo, "Brevo", $descr="SMTP", $tags="", $link="")
System(Cloudinary, "Cloudinary", $descr="Media Management SaaS", $tags="", $link="")

Rel(TaskManagement, Cloudinary, "Reads from and writes to", $techn="HTTPS/REST", $tags="", $link="")
Rel(TaskManagement, Brevo, "Reads from and writes to", $techn="HTTPS/REST", $tags="", $link="")
Rel(User, TaskManagement, "Add project, task, comment, ...", $techn="", $tags="", $link="")
Rel(Administrator, TaskManagement, "Manage user, workspace, project, task, comment, ...", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
hide stereotypes
@enduml