@startuml
title <size:24>Dynamic View: Task Management</size>\n<size:24>Luồng xóa Task và trigger xóa Comment qua Event</size>

set separator none
left to right direction

<style>
  root {
    BackgroundColor: #ffffff
    FontColor: #444444
  }
</style>

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>

System_Boundary("TaskManagement_boundary", "Task Management", $tags="") {
  Container(TaskManagement.TaskService, "Task Service", $techn="Spring Boot", $descr="Task Service", $tags="", $link="")
  Container(TaskManagement.UI, "UI", $techn="React", $descr="Single Page Application", $tags="", $link="")
  Container(TaskManagement.CommentService, "Comment Service", $techn="Spring Boot", $descr="Comment Service", $tags="", $link="")
  Container(TaskManagement.APIGateway, "API Gateway", $techn="Spring Cloud Gateway", $descr="API Gateway", $tags="", $link="")
  ContainerQueue(TaskManagement.MessageBroker, "Message Broker", $techn="RabbitMQ", $descr="Message Broker", $tags="", $link="")
  ContainerDb(TaskManagement.TaskDB, "Task DB", $techn="PostgreSQL", $descr="RDBMS", $tags="", $link="")
  ContainerDb(TaskManagement.CommentDB, "Comment DB", $techn="MongoDB", $descr="Document Store", $tags="", $link="")
}

Person(User, "User", $descr="End User", $tags="", $link="")

Rel(User, TaskManagement.UI, "1: 1. Bấm xóa Task", $techn="", $tags="", $link="")
Rel(TaskManagement.UI, TaskManagement.APIGateway, "2: 2. DELETE /api/tasks/{id}", $techn="JSON/HTTP", $tags="", $link="")
Rel(TaskManagement.APIGateway, TaskManagement.TaskService, "3: 3. Xóa Task trong DB", $techn="", $tags="", $link="")
Rel(TaskManagement.TaskService, TaskManagement.TaskDB, "4: 4. Xóa  Task", $techn="JDBC", $tags="", $link="")
Rel(TaskManagement.TaskService, TaskManagement.MessageBroker, "5: 5. Publish 'task.deleted' event", $techn="", $tags="", $link="")
Rel(TaskManagement.CommentService, TaskManagement.MessageBroker, "6: 6. Subscribe event", $techn="", $tags="", $link="")
Rel(TaskManagement.CommentService, TaskManagement.CommentDB, "7: 7. Xóa toàn bộ Comment của Task", $techn="MongoDB Wire Protocol", $tags="", $link="")

SHOW_LEGEND(true)
hide stereotypes
@enduml