@startuml
title <size:24>Component View: Authentication Service</size>\n<size:24>The component diagram for a Authentication Service</size>

set separator none
top to bottom direction

<style>
  root {
    BackgroundColor: #ffffff
    FontColor: #444444
  }
</style>

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>
!include <C4/C4_Component>

System_Boundary("TaskManagement_boundary", "Task Management", $tags="") {
  Container_Boundary("TaskManagement.AuthenticationService_boundary", "Authentication Service", $tags="") {
    Component(TaskManagement.AuthenticationService.SecurityFilterChain, "Security Filter Chain", $techn="Spring Security", $descr="Security Filter Chain", $tags="", $link="")
    Component(TaskManagement.AuthenticationService.Controller, "Controller", $techn="Spring", $descr="Controller", $tags="", $link="")
    Component(TaskManagement.AuthenticationService.Service, "Service", $techn="Spring", $descr="Service", $tags="", $link="")
    Component(TaskManagement.AuthenticationService.Repository, "Repository", $techn="Spring", $descr="Repository", $tags="", $link="")
    Component(TaskManagement.AuthenticationService.Scheduler, "Scheduler", $techn="Spring", $descr="Scheduler", $tags="", $link="")
    Component(TaskManagement.AuthenticationService.Producer, "Producer", $techn="Spring", $descr="Producer", $tags="", $link="")
  }

  Container(TaskManagement.APIGateway, "API Gateway", $techn="Spring Cloud Gateway", $descr="API Gateway", $tags="", $link="")
  ContainerQueue(TaskManagement.MessageBroker, "Message Broker", $techn="RabbitMQ", $descr="Message Broker", $tags="", $link="")
  ContainerDb(TaskManagement.AuthenticationDB, "Authentication DB", $techn="PostgreSQL", $descr="RDBMS", $tags="", $link="")
}

Rel(TaskManagement.AuthenticationService.SecurityFilterChain, TaskManagement.AuthenticationService.Controller, "", $techn="", $tags="", $link="")
Rel(TaskManagement.AuthenticationService.Controller, TaskManagement.AuthenticationService.Service, "", $techn="", $tags="", $link="")
Rel(TaskManagement.AuthenticationService.Service, TaskManagement.AuthenticationService.Repository, "", $techn="", $tags="", $link="")
Rel(TaskManagement.AuthenticationService.Scheduler, TaskManagement.AuthenticationService.Repository, "", $techn="", $tags="", $link="")
Rel(TaskManagement.AuthenticationService.Scheduler, TaskManagement.AuthenticationService.Producer, "", $techn="", $tags="", $link="")
Rel(TaskManagement.APIGateway, TaskManagement.AuthenticationService.SecurityFilterChain, "Forward", $techn="", $tags="", $link="")
Rel(TaskManagement.AuthenticationService.Producer, TaskManagement.MessageBroker, "Publish event", $techn="", $tags="", $link="")
Rel(TaskManagement.AuthenticationService.Repository, TaskManagement.AuthenticationDB, "Reads from and writes to", $techn="JDBC", $tags="", $link="")

SHOW_LEGEND(true)
hide stereotypes
@enduml