name: CI

on:
  push:
    branches: [ master ]
    paths:
      - 'backend/**'
      - 'frontend/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'backend/**'
      - 'frontend/**'

jobs:
  detect-changes:
    name: Detect Changes
    uses: ./.github/workflows/detect-changes.yml
    permissions:
      contents: read
      pull-requests: read

  format-code:
    name: Auto Format Code
    runs-on: ubuntu-latest
    needs: detect-changes
    if: |
      needs.detect-changes.outputs['authentication-service'] == 'true' ||
      needs.detect-changes.outputs['profile-service'] == 'true' ||
      needs.detect-changes.outputs['task-service'] == 'true' ||
      needs.detect-changes.outputs['comment-service'] == 'true' ||
      needs.detect-changes.outputs['notification-service'] == 'true' ||
      needs.detect-changes.outputs['api-gateway'] == 'true'
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run Spotless
        working-directory: ./backend
        run: mvn spotless:apply --batch-mode --no-transfer-progress

      - name: Auto commit by bot
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style(project): auto-format code by Spotless [skip ci]"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"

  build-and-test:
    name: Test ${{ matrix.service }}
    runs-on: ubuntu-latest
    needs: [ detect-changes, format-code ]
    if: always() && needs.detect-changes.result == 'success'
    strategy:
      fail-fast: false
      matrix:
        include:
          - service: authentication-service
            changed: ${{ needs.detect-changes.outputs['authentication-service'] }}
          - service: profile-service
            changed: ${{ needs.detect-changes.outputs['profile-service'] }}
          - service: task-service
            changed: ${{ needs.detect-changes.outputs['task-service'] }}
          - service: comment-service
            changed: ${{ needs.detect-changes.outputs['comment-service'] }}
          - service: notification-service
            changed: ${{ needs.detect-changes.outputs['notification-service'] }}
          - service: api-gateway
            changed: ${{ needs.detect-changes.outputs['api-gateway'] }}
    permissions:
      contents: read
    steps:
      - name: Skip if not changed
        if: matrix.changed != 'true'
        run: echo "No changes in ${{ matrix.service }}, skipping."

      - name: Checkout code
        if: matrix.changed == 'true'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Set up JDK 21
        if: matrix.changed == 'true'
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build and Test
        if: matrix.changed == 'true'
        working-directory: ./backend/${{ matrix.service }}
        run: mvn verify --batch-mode --no-transfer-progress

      - name: Upload Test Results
        if: matrix.changed == 'true' && always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.service }}
          path: backend/${{ matrix.service }}/target/surefire-reports/*.xml
          retention-days: 1

      - name: Upload Coverage Results
        if: matrix.changed == 'true' && always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report-${{ matrix.service }}
          path: backend/${{ matrix.service }}/target/site/jacoco/jacoco.xml
          retention-days: 1

  ci-summary:
    name: CI Summary
    runs-on: ubuntu-latest
    needs: [ detect-changes, build-and-test ]
    if: always()
    permissions:
      checks: write
      pull-requests: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: false

      - name: Generate CI Summary
        env:
          AUTHENTICATION_SERVICE_CHANGED: ${{ needs.detect-changes.outputs['authentication-service'] }}
          PROFILE_SERVICE_CHANGED: ${{ needs.detect-changes.outputs['profile-service'] }}
          TASK_SERVICE_CHANGED: ${{ needs.detect-changes.outputs['task-service'] }}
          COMMENT_SERVICE_CHANGED: ${{ needs.detect-changes.outputs['comment-service'] }}
          NOTIFICATION_SERVICE_CHANGED: ${{ needs.detect-changes.outputs['notification-service'] }}
          API_GATEWAY_CHANGED: ${{ needs.detect-changes.outputs['api-gateway'] }}
        run: |
          echo "## Test Summary" >> $GITHUB_STEP_SUMMARY
          echo "| Service | Status | Coverage | Total Test | Pass | Fail | Skip |" >> $GITHUB_STEP_SUMMARY
          echo "|-------------------|------------|------------|-----------|------|------|------|" >> $GITHUB_STEP_SUMMARY
          
          SERVICES=("authentication-service" "profile-service" "task-service" "comment-service" "notification-service" "api-gateway")
          
          for svc in "${SERVICES[@]}"; do
            var_name=$(echo "${svc}_changed" | tr '-' '_' | tr 'a-z' 'A-Z')
            changed=${!var_name}
          
            if [ "$changed" == "true" ]; then
              STATUS="Success"
              COV="0%"
              XML_FILE="artifacts/jacoco-report-${svc}/jacoco.xml"
          
              if [ -f "$XML_FILE" ]; then
                INSTRUCTION_TAG=$(grep -o '<counter type="INSTRUCTION"[^>]*>' "$XML_FILE" | tail -n 1)
                if [ -n "$INSTRUCTION_TAG" ]; then
                  MISSED=$(echo "$INSTRUCTION_TAG" | grep -o 'missed="[0-9]*"' | cut -d'"' -f2)
                  COVERED=$(echo "$INSTRUCTION_TAG" | grep -o 'covered="[0-9]*"' | cut -d'"' -f2)
                  if [ -n "$MISSED" ] && [ -n "$COVERED" ]; then
                    TOTAL=$((MISSED + COVERED))
                    if [ $TOTAL -gt 0 ]; then
                      COV=$((COVERED * 100 / TOTAL))"%"
                    fi
                  fi
                fi
              else
                COV="Can not read XML file"
              fi
          
              TOTAL_TESTS=0; PASS_TESTS=0; FAIL_TESTS=0; SKIP_TESTS=0
              for test_file in artifacts/test-results-${svc}/*.xml; do
                if [ -f "$test_file" ]; then
                   T=$(grep -m 1 '<testsuite ' "$test_file" | grep -o 'tests="[0-9]*"' | cut -d'"' -f2)
                   F=$(grep -m 1 '<testsuite ' "$test_file" | grep -o 'failures="[0-9]*"' | cut -d'"' -f2)
                   E=$(grep -m 1 '<testsuite ' "$test_file" | grep -o 'errors="[0-9]*"' | cut -d'"' -f2)
                   S=$(grep -m 1 '<testsuite ' "$test_file" | grep -o 'skipped="[0-9]*"' | cut -d'"' -f2)
          
                   TOTAL_TESTS=$((TOTAL_TESTS + ${T:-0}))
                   FAIL_TESTS=$((FAIL_TESTS + ${F:-0} + ${E:-0}))
                   SKIP_TESTS=$((SKIP_TESTS + ${S:-0}))
                fi
              done
              PASS_TESTS=$((TOTAL_TESTS - FAIL_TESTS - SKIP_TESTS))
          
              echo "| **$svc** | $STATUS | **$COV** | $TOTAL_TESTS | $PASS_TESTS | $FAIL_TESTS | $SKIP_TESTS |" >> $GITHUB_STEP_SUMMARY
            else
              echo "| $svc | Skipped | - | - | - | - | - |" >> $GITHUB_STEP_SUMMARY
            fi
          done